### ISSUE TITLE
comparison with Object.assign() and deepmerge

### ISSUE THREAD

**Issue by DanielRuf** [numanelahi/easy-patch#1]
`deepmerge` and `Object.assign()` already do these things (merge them into one) and also `lodash` and `underscore`.

So what does easy-patch do that is different from these solutions?

Also the JSON patch specification is about something different (a file for PATCH requests which is processed then).

**Comment by DanielRuf** [comment]
Hi, I hoped to get some replies.

Well, I think it is the best to update the readme to clarify what this library does and so on =)

**Comment by numanelahi** [comment]
Hola, actually I tried to implement RFC6902 in a way so that it works like deepmerge. I could just add appending to array feature to it after that didn't get time to work on it.
